# theme = "everforest_light_hard"
# theme = "everforest_light_medium"
theme = "everforest_light_soft"

[editor]
mouse = false
rulers = [97]
cursorline = true
cursorcolumn = true
bufferline = "multiple"
line-number = "relative"

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [ "mode", "file-name", "file-modification-indicator", "spinner", "diagnostics" ]
right = [ "selections","position", "position-percentage", "total-line-numbers" ]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.indent-guides]
render = true
character = "|" 
skip-levels = 1

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
