[[sources]] # list of sources to load
name = "friendly-snippets"  # optional name shown on snippet description
git = "https://github.com/rafamadriz/friendly-snippets.git"

# define one of snippets path inside this repo
[[sources.paths]]
scope = ["python"] 
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["scala"] 
path = "snippets/scala.json"

[[sources.paths]]
scope = ["c"] 
path = "snippets/c/c.json"

[[sources.paths]]
scope = ["cpp"] 
path = "snippets/cpp/cpp.json"

[[sources.paths]]
scope = ["rust"] 
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["make"] 
path = "snippets/make.json"

[[sources.paths]]
scope = ["latex"] 
path = "snippets/latex/latex-snippets.json"
