syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

set langmenu=en
let $LANG='en'
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gb2312,gbk,gb18030

set nocompatible

set number
set relativenumber
set history=100

set cursorline
set wrap
set showcmd
set wildmenu

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4

set showmatch

set vb t_vb=

set ruler

" search
set nohls
set incsearch
set ignorecase
set smartcase

" Insert Mode
" auto complete
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap " ""<ESC>i

colorscheme delek
" Set <LEADER> as <SPACE>
let mapleader=" "

" Normal Mode
nmap s <nop>
nmap sr :set splitright<CR>:vsplit<CR>
nmap sl :set nosplitright<CR>:vsplit<CR>

map <LEADER>k <C-w>k
map <LEADER>j <C-w>j
map <LEADER>h <C-w>h
map <LEADER>l <C-w>l
