# bind to another prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# tmux有一个延时以方便用户按键组合，默认有点长。这里设置为1秒钟
set -s escape-time 1

# mode-keys
setw -g mode-keys vi

# display color
set -g default-terminal "screen-256color"
