syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

set langmenu=en
let $LANG='en'
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gb2312,gbk,gb18030

set nocompatible

set number
set relativenumber
set history=100

set cursorline
set wrap
set showcmd
set wildmenu

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4

set showmatch

set vb t_vb=

set ruler

" search
set nohls
set incsearch
set ignorecase
set smartcase

" Insert Mode
" auto complete
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap " ""<ESC>i

" Normal Mode
nmap s <nop>
nmap S :w<CR>
nmap Q :q<CR>
nmap R :source $MYVIMRC<CR>
nmap rr :set splitright<CR>:vsplit<CR>
nmap rl :set nosplitright<CR>:vsplit<CR>
nmap <C-d> <C-f>

" gVim
set guifont=Consolas:h12

" https://github.com/junegunn/vim-plug
" ############# Linux ############# 
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"call plug#begin('~/.vim/plugged')
" ############# Windows ############# 
"call plug#begin('~/vimfiles/plugged')

Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
Plug 'lervag/vimtex'

call plug#end()

" ############# Vimtex ############# 
let g:tex_flavor='latexmk'
let g:vimtex_texcount_custom_arg=' -ch -total'
au FileType tex map <buffer> <silent>  <leader>lw :VimtexCountWords!  <CR><CR>
"" ############# SumatraPDF ############# 
"let g:Tex_ViewRule_pdf = '~\AppData\Local\SumatraPDF\SumatraPDF.exe -reuse-instance -inverse-search "gvim -c \":RemoteOpen +\%l \%f\""'
"" ############# Zathura ############# 
"let g:vimtex_view_method='zathura'
" show the compiler hint
let g:vimtex_quickfix_mode=1
" hide the last two lines
set conceallevel=1
let g:tex_conceal='abdmg'
