syntax on 
filetype on 
filetype indent on
filetype plugin on
filetype plugin indent on

set langmenu=en
let $LANG='en'
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gb2312,gbk,gb18030

set nocompatible

set number
set relativenumber
set history=100 

set cursorline
set wrap
set showcmd
set wildmenu

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4

set showmatch

set vb t_vb=

set ruler

" search
set nohls
set incsearch
set ignorecase
set smartcase

" auto complete
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap " ""<ESC>i

" mapping
map s <nop>
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>
cmap rr :set splitright<CR>:vsplit<CR>
cmap rl :set nosplitright<CR>:vsplit<CR>
cmap <C-d> <C-f>

" FOR gVim
set guifont=Consolas:h12
