syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on

set langmenu=en
let $LANG='en'
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gb2312,gbk,gb18030

set nocompatible

set number
set relativenumber
set history=100

set cursorline
set wrap
set showcmd
set wildmenu

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4

set showmatch

set vb t_vb=

set ruler

" search
set nohls
set incsearch
set ignorecase
set smartcase

" Insert Mode
" auto complete
inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap " ""<ESC>i

" Normal Mode
nmap s <nop>
nmap S :w<CR>
nmap Q :q<CR>
nmap R :source $MYVIMRC<CR>
nmap rr :set splitright<CR>:vsplit<CR>
nmap rl :set nosplitright<CR>:vsplit<CR>
nmap <C-d> <C-f>

" for gVim
set guifont=Consolas:h12

" vim plugin: https://github.com/junegunn/vim-plug
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
call plug#end()
