general.live_config_reload = true
[window]
padding = { x = 7, y = 7}
dimensions = { columns = 150, lines = 30}
opacity = 1.0

[env]
TERM = 'xterm-256color'

# Colors (Everforest Light)
[colors.primary]
background = '#fdf6e3'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

# Bright Colors
[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

[font]
size = 12

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'Regular'

[font.bold]
family = 'JetBrainsMono Nerd Font'

[font.italic]
family = 'JetBrainsMono Nerd Font'

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "Copy"
